const blogs = [
  {
    title: 'Learn in a Redux Way',
    bannar: 'hotel-1.jpg',
    author: 'Learn With Sumit',
    avatar: 'https://avatars.githubusercontent.com/u/73503432?v=4',
  },

  {
    title: 'Make Search Engine Using Python',
    bannar: 'hotel-2.jpg',
    author: 'Web Dev Simplified',
    avatar: 'https://avatars.githubusercontent.com/u/39717099?s=100&v=4',
  },
  {
    title: 'Create Self Driving Car using JAVA',
    bannar: 'hotel-3.jpg',
    author: 'Brad Traversy',
    avatar: 'https://avatars.githubusercontent.com/u/5550850?s=100&v=4',
  },
  {
    title: 'Build Amazon Using Nodejs',
    bannar: 'hotel-4.jpg',
    author: 'Fayzul Karim',
    avatar: 'https://avatars.githubusercontent.com/u/497812?s=100&v=4',
  },
  {
    title: 'How to make alexa using python',
    bannar: 'hotel-5.jpg',
    author: 'Brad Traversy',
    avatar: 'https://avatars.githubusercontent.com/u/5550850?s=100&v=4',
  },
  {
    title: 'Improve your Php Experiance',
    bannar: 'hotel-6.jpg',
    author: 'Hasin Hayder',
    avatar: 'https://avatars.githubusercontent.com/u/490779?s=100&v=4',
  },
  {
    title: 'Hack NASA Using PHP',
    bannar: 'hotel-7.jpg',
    author: 'Learn With Sumit',
    avatar: 'https://avatars.githubusercontent.com/u/73503432?v=4',
  },
  {
    title: 'Learn Redux Toolkit',
    bannar: 'hotel-8.jpg',
    author: 'Brad Traversy',
    avatar: 'https://avatars.githubusercontent.com/u/5550850?s=100&v=4',
  },
]

const UsersData = [
  {
    name: 'John Smith',
    password: 'Password@1234',
    email: 'jsmith@example.com',
    mobile: '01760000005',
    about: 'I am a software engineer.',
    dob: '1990-01-01',
    gender: 'male',
  },
  {
    name: 'Jane Doe',
    password: 'Password@1234',
    email: 'jdoe@example.com',
    mobile: '01760000006',
    about: 'I am a marketing specialist.',
    dob: '1992-02-01',
    gender: 'female',
  },
  {
    name: 'David Lee',
    password: 'Password@1234',
    email: 'dlee@example.com',
    mobile: '01760000007',
    about: 'I am a business analyst.',
    dob: '1988-03-01',
    gender: 'male',
  },
  {
    name: 'Maria Rodriguez',
    password: 'Password@1234',
    email: 'mrodriguez@example.com',
    mobile: '01760000008',
    about: 'I am a graphic designer.',
    dob: '1995-04-01',
    gender: 'female',
  },
  {
    name: 'Chris Johnson',
    password: 'Password@1234',
    email: 'cjohnson@example.com',
    mobile: '01760000009',
    about: 'I am a fitness trainer.',
    dob: '1993-05-01',
    gender: 'male',
  },
  {
    name: 'Samantha Lee',
    password: 'Password@1234',
    email: 'slee@example.com',
    mobile: '01760000010',
    about: 'I am a writer.',
    dob: '1991-06-01',
    gender: 'female',
  },
  {
    name: 'Michael Kim',
    password: 'Password@1234',
    email: 'mkim@example.com',
    mobile: '01760000011',
    about: 'I am a software developer.',
    dob: '1989-07-01',
    gender: 'male',
  },
  {
    name: 'Amanda Nguyen',
    password: 'Password@1234',
    email: 'anguyen@example.com',
    mobile: '01760000012',
    about: 'I am a human resources specialist.',
    dob: '1994-08-01',
    gender: 'female',
  },
  {
    name: 'Mark Brown',
    password: 'Password@1234',
    email: 'mbrown@example.com',
    mobile: '01760000013',
    about: 'I am a sales representative.',
    dob: '1996-09-01',
    gender: 'male',
  },
  {
    name: 'Laura Martinez',
    password: 'Password@1234',
    email: 'lmartinez@example.com',
    mobile: '01760000014',
    about: 'I am a customer service representative.',
    dob: '1997-10-01',
    gender: 'female',
  },
]

module.exports = {
  blogs,
}
